apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: webhookbin-rollout
    app.kubernetes.io/name: webhookbin-rollout
    app.kubernetes.io/version: 1.16.0
  name: webhookbin-rollout-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: webhookbin-rollout
    app.kubernetes.io/name: webhookbin-rollout
  type: ClusterIP
status:
  loadBalancer: {}
