apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: a24f40d7-5a72-41a9-a2ce-8510701e7aec
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: webhookbin-rollout
    app.kubernetes.io/name: webhookbin-rollout
    app.kubernetes.io/version: 1.16.0
  name: webhookbin-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: webhookbin-rollout
      app.kubernetes.io/name: webhookbin-rollout
  strategy:
    canary:
      canaryService: webhookbin-rollout-canary
      stableService: webhookbin-rollout
      steps:
      - setWeight: 10
      - pause:
          duration: 12
      - setWeight: 20
      - pause:
          duration: 12
      - setWeight: 30
      - pause:
          duration: 12
      - setWeight: 40
      - pause:
          duration: 12
      - setWeight: 50
      - pause:
          duration: 12
      - setWeight: 60
      - pause:
          duration: 12
      - setWeight: 70
      - pause:
          duration: 12
      - setWeight: 80
      - pause:
          duration: 12
      - setWeight: 90
      - pause:
          duration: 12
      - setWeight: 100
      - pause:
          duration: 12
      trafficRouting:
        ambassador:
          mappings:
          - webhookbin-rollout
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: webhookbin-rollout
        app.kubernetes.io/name: webhookbin-rollout
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: grangerp/webhookbin:0.2
        imagePullPolicy: IfNotPresent
        name: webhookbin-rollout
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
      securityContext: {}
status:
  blueGreen: {}
  canary: {}
