apiVersion: v1
kind: Service
metadata:
  name: webhookbin-rollout
  labels:
    app.kubernetes.io/name: webhookbin-rollout
    app.kubernetes.io/instance: webhookbin-rollout
    app.kubernetes.io/version: "1.16.0"
  annotations:
    a8r.io/description: "Record webhook"
    a8r.io/owner: "@grangerp"
    a8r.io/bugs: "https://github.com/grangerp/webhookbin/issues"
    a8r.io/repository: "https://github.com/grangerp/webhookbin"
    a8r.io/rollouts.scm.branch: "dev"
    a8r.io/rollouts.scm.path: "manifests-rollout"
    a8r.io/rollouts.image-repo.type: "dockerhub"
    a8r.io/rollouts.image-repo.name: "grangerp/webhookbin"
    a8r.io/rollouts.deployment: "webhookbin-rollout"
    a8r.io/rollouts.mappings: "webhookbin-rollout"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webhookbin-rollout
    app.kubernetes.io/instance: webhookbin-rollout
